### PR TITLE
Add XHR Headers Option

### PR DESCRIPTION
**Pull request by ThembaniFubesi**
Add option to allow for xhr headers.

This is useful if you are trying to download files for an API with basic auth or there are extra headers you would like to send with your request.

### CODE REVIEW

**Comment by benjaminmwilson** [comment]
Thanks Thembani. This is a nice addition!

**Comment by benjaminmwilson** [comment]
Merging...

**Review by benjaminmwilson — COMMENTED** [review]
looks good

**Comment by ThembaniFubesi** [comment]
Awesome.

**Pull request merged**
